name = "Survey"
uuid = "86ae7f4d-a3c3-41ee-997a-11fba81b51ba"
authors = ["Mamadou S Diallo <me@msdiallo.io> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
